linters:

   
   
 
   eslint:
       config: './eslint.config'
   csslint:
       config: './csslint.config'
   fixers:
        enable: true
       
       
       
files:
 ignore:
   - 'bower_components/*'
   - 'node_modules/*'

